export const CustomerCollections = {
  USERS: "users",
  USER_PROFILES: "user_profiles",
  USER_GROUPS: "user_groups",
  ROLES: "roles",
  PERMISSIONS: "permissions",
  SERVICES: "services",
  CATEGORIES: "categories",
  PROVIDERS: "providers",
  PROVIDER_SERVICES: "provider_services",
  SERVICE_PRICES: "service_prices",
  ORDERS: "orders",
  ORDER_STATUS_HISTORY: "order_status_history",
  WALLETS: "wallets",
  WALLET_TRANSACTIONS: "wallet_transactions",
  PAYMENTS: "payments",
  PAYMENT_WEBHOOKS: "payment_webhooks",
  PAYMENT_TRANSACTIONS: "payment_transactions",
  REFILLS: "refills",
  DRIP_FEED_ORDERS: "drip_feed_orders",
  DRIP_FEED_RUNS: "drip_feed_runs",
  SUBSCRIPTIONS: "subscriptions",
  SUBSCRIPTION_RUNS: "subscription_runs",
  API_KEYS: "api_keys",
  API_LOGS: "api_logs",
  REFERRALS: "referrals",
  REFERRAL_COMMISSIONS: "referral_commissions",
  PAYOUT_REQUESTS: "payout_requests",
  COUPONS: "coupons",
  COUPON_REDEMPTIONS: "coupon_redemptions",
  TICKETS: "tickets",
  TICKET_MESSAGES: "ticket_messages",
  TICKET_ATTACHMENTS: "ticket_attachments",
  NOTIFICATIONS: "notifications",
  ANNOUNCEMENTS: "announcements",
  EMAIL_TEMPLATES: "email_templates",
  EMAIL_LOGS: "email_logs",
  SETTINGS: "settings",
  PAGES: "pages",
  BLOGS: "blogs",
  BLOG_CATEGORIES: "blog_categories",
  TRANSLATIONS: "translations",
  THEMES: "themes",
  CHILD_PANELS: "child_panels",
  AUDIT_LOGS: "audit_logs",
  SYSTEM_LOGS: "system_logs",
  SESSIONS: "sessions",
  LICENSE_STATE: "license_state",
} as const;

export type CustomerCollection = (typeof CustomerCollections)[keyof typeof CustomerCollections];

export const LicenseCollections = {
  LICENSE_PRODUCTS: "license_products",
  LICENSE_CLIENTS: "license_clients",
  LICENSES: "licenses",
  LICENSE_INSTALLATIONS: "license_installations",
  LICENSE_ACTIVATIONS: "license_activations",
  LICENSE_VALIDATIONS: "license_validations",
  LICENSE_EVENTS: "license_events",
  LICENSE_ADMINS: "license_admins",
  LICENSE_ROLES: "license_roles",
  LICENSE_PERMISSIONS: "license_permissions",
  PRODUCT_VERSIONS: "product_versions",
  PRODUCT_RELEASES: "product_releases",
  LICENSE_AUDIT_LOGS: "license_audit_logs",
} as const;

export type LicenseCollection =
  (typeof LicenseCollections)[keyof typeof LicenseCollections];